name: Build

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
    paths-ignore: 
      - '**.md'
  pull_request:
    branches:
      - master
      - release-*
    paths-ignore: 
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: Deprecated
      run: |
        # This build is deprecared. Keeping it so PR can be merged.
        echo "Done."